name: DSLA Protocol's StatusPage Public API Service Level Agreement (SLA)
description: A Public StatusPage Chainlink external adapter for DSLA Protocol.
node_identifier: dsla-oracle-statuspage
platforms:
  - GCP Functions
data_sources:
  - name: StatusPageURL
    description: A URL is provided for a public StatusPage API that has a v2 endpoint with an incidents.json file.
parameters:
  - sla_address
  - network_name
  - period_start
  - period_end